### PR TITLE
Changed user interface

### PR DESCRIPTION
**Pull request by ghost**
backcraft
 (Sorry if there's something wrong. I'm new to github, so I don't know exactly what I'm doing)

### CODE REVIEW

**Comment by emimontesdeoca** [comment]
Wow, incredible design! 

Right now I'm developing v3.0 and I've actually changed almost everything, this is because thanks of the redditors feedback some new features are on the way:

- MD5 scan for every backup, as pointed [here](https://github.com/emimontesdeoca/Backcraft/issues/2)
- Selecting which world or which texture pack you want to save, written [here](https://www.reddit.com/r/Minecraft/comments/6n9oki/hello_rminecraft_after_losing_my_hardcore_map_i/dk8po7z/).
- Some improvements in style like slider for interval.

Overall I am completely fascinated by your style, I would like to know if you would like customize this next version also.

This is an image of the current version in development, I do not plan to change anything relating the views, all that is missing are logic related.

v3

**Comment by ghost** [comment]
@emimontesdeoca Sure. I can begin working on it later today. Also, would be happy to help with the coding part if need be.

**Comment by emimontesdeoca** [comment]
Great work​!!! 

Going to check it out as soon as I get to my PC, just recently pushed some code that stores all states in a single file(before it had a class for each state), if you want you can check it out and give some advice for some optimization or improvements, feel free to do it.

**Comment by emimontesdeoca** [comment]
New UI is needed since this style is for the old one.

**Comment by ghost** [comment]
On it!

**Pull request closed without merging**
